# Generated by Django 5.2.7 on 2025-10-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('zoho_id', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_1', models.CharField(blank=True, max_length=100, null=True)),
                ('pt_date', models.DateField(blank=True, null=True)),
                ('ft_date', models.DateField(blank=True, null=True)),
                ('last_day', models.DateField(blank=True, null=True)),
                ('salaire_net', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('devise', models.CharField(blank=True, max_length=10, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('accomodation', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_company', models.CharField(blank=True, max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_country', models.CharField(blank=True, max_length=100, null=True)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('swift', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
