# Generated by Django 5.2.7 on 2025-11-02 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_import',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
