# Generated by Django 5.2.7 on 2025-11-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_date_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='iban',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='swift',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
