# Generated by Django 5.2.7 on 2025-11-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_bank_name_alter_employee_iban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='lead_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
