# Generated by Django 5.2.7 on 2025-10-30 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField(help_text='Premier jour du mois concerné (ex: 2025-10-01)')),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('devise', models.CharField(default='AED', max_length=10)),
                ('heures_supp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_heures_supp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remboursement', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remboursement_comment', models.TextField(blank=True, null=True)),
                ('nb_conges', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('autres', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('autres_comment', models.TextField(blank=True, null=True)),
                ('total_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee')),
            ],
            options={
                'db_table': 'payroll',
                'ordering': ['-periode', 'employee_id'],
                'unique_together': {('employee', 'periode')},
            },
        ),
    ]
