# Generated by Django 5.2.7 on 2025-11-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payroll_autres_alter_payroll_deduction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-periode', 'employee__nom']},
        ),
        migrations.AlterField(
            model_name='payroll',
            name='devise',
            field=models.CharField(default='EUR', max_length=10),
        ),
        migrations.AlterModelTable(
            name='payroll',
            table=None,
        ),
    ]
