# Generated by Django 5.2.7 on 2025-11-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payroll_options_alter_payroll_devise_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payroll',
            table='payroll',
        ),
    ]
