# Generated by Django 5.2.7 on 2025-11-02 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_lead_1'),
        ('payroll', '0004_alter_payroll_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-periode', 'id'], 'verbose_name': 'Fiche de paie', 'verbose_name_plural': 'Fiches de paie'},
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee', verbose_name='Employé'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='periode',
            field=models.DateField(verbose_name='Période'),
        ),
    ]
